import { useEffect, useState } from 'react';
import { Link, NavLink, Route, Routes, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { api } from './api';
import { EmptyState, ErrorState, LoadingGrid, MovieGrid } from './components';
import type { Movie, PageResult } from './types';
function Layout({ children }: { children: React.ReactNode }) { return <main className="app-shell"><nav className="nav"><Link className="brand" to="/">Reel<span>Scout</span></Link><div className="nav-links"><NavLink to="/" end>Discover</NavLink><NavLink to="/wishlist">Wishlist</NavLink></div></nav>{children}</main>; }
function useWishlist() { const [wishlist, setWishlist] = useState<Movie[]>([]); useEffect(() => { api.wishlist().then(r => setWishlist(r.data)).catch(() => undefined); }, []); const toggle = async (movie: Movie) => { const exists = wishlist.some(item => item.id === movie.id); const result = exists ? await api.removeWishlist(movie.id) : await api.addWishlist(movie); setWishlist(result.data); }; return { wishlist, toggle }; }
function SearchBox({ initial = '' }: { initial?: string }) { const navigate = useNavigate(); const [value, setValue] = useState(initial); return <form className="search-bar" onSubmit={e => { e.preventDefault(); if (value.trim()) navigate(`/search?q=${encodeURIComponent(value.trim())}`); }}><input value={value} onChange={e => setValue(e.target.value)} placeholder="Search for a movie..." aria-label="Search for a movie" /><button>Search</button></form>; }
function Pagination({ result, page, setPage }: { result: PageResult; page: number; setPage: (page: number) => void }) { return <div className="pagination"><button disabled={page <= 1} onClick={() => setPage(page - 1)}>Previous</button><span>Page {page} of {Math.max(1, Math.min(result.pagination.totalPages, 500))}</span><button disabled={!result.pagination.hasNextPage || page >= 500} onClick={() => setPage(page + 1)}>Next</button></div>; }
function Discover() { const { wishlist, toggle } = useWishlist(); const [page, setPage] = useState(1); const [genre, setGenre] = useState(''); const [sortBy, setSortBy] = useState('popularity.desc'); const [result, setResult] = useState<PageResult>(); const [error, setError] = useState(''); useEffect(() => { setError(''); api.discover(page, genre, sortBy).then(setResult).catch(e => setError(e.message)); }, [page, genre, sortBy]); return <><section className="hero"><div className="eyebrow">Find your next favorite</div><h1>Stories worth staying up for.</h1><p>Explore popular, surprising, and unforgettable films from one calm, focused discovery space.</p><SearchBox /></section><div className="section-head"><h2>Discover movies</h2><div className="controls"><select value={genre} onChange={e => { setGenre(e.target.value); setPage(1); }} aria-label="Filter by genre"><option value="">All genres</option><option>Action</option><option>Adventure</option><option>Animation</option><option>Comedy</option><option>Drama</option><option>Mystery</option><option>Science Fiction</option><option>Thriller</option></select><select value={sortBy} onChange={e => { setSortBy(e.target.value); setPage(1); }} aria-label="Sort movies"><option value="popularity.desc">Most popular</option><option value="vote_average.desc">Highest rated</option><option value="primary_release_date.desc">Newest</option></select></div></div>{error ? <ErrorState message={error} retry={() => setPage(page)} /> : !result ? <LoadingGrid /> : result.data.length === 0 ? <EmptyState title="No movies found" message="Try changing your filters." /> : <><MovieGrid movies={result.data} wishlist={wishlist} onToggle={toggle} /><Pagination result={result} page={page} setPage={setPage} /></>}</>; }
function SearchPage() { const [params] = useSearchParams(); const query = params.get('q') ?? ''; const { wishlist, toggle } = useWishlist(); const [page, setPage] = useState(1); const [result, setResult] = useState<PageResult>(); const [error, setError] = useState(''); useEffect(() => { setPage(1); if (query.length < 2) return; setError(''); api.search(query, page).then(setResult).catch(e => setError(e.message)); }, [query, page]); return <><section className="hero"><div className="eyebrow">Search results</div><h1>Results for “{query}”.</h1><SearchBox initial={query} /></section>{error ? <ErrorState message={error} retry={() => setPage(page)} /> : !result ? <LoadingGrid /> : result.data.length === 0 ? <EmptyState title="Nothing matched" message="Try a different title or search phrase." /> : <><MovieGrid movies={result.data} wishlist={wishlist} onToggle={toggle} /><Pagination result={result} page={page} setPage={setPage} /></>}</>; }
function WishlistPage() { const { wishlist, toggle } = useWishlist(); return <><section className="hero"><div className="eyebrow">Your collection</div><h1>Saved for later.</h1><p>Your personal shortlist is kept on this device so it is ready when you return.</p></section>{wishlist.length ? <MovieGrid movies={wishlist} wishlist={wishlist} onToggle={toggle} /> : <EmptyState title="Your wishlist is empty" message="Save a movie while browsing and it will appear here." />}</>; }
function DetailsPage() { const { id } = useParams(); const { wishlist, toggle } = useWishlist(); const [movie, setMovie] = useState<Movie>(); const [error, setError] = useState(''); useEffect(() => { api.details(Number(id)).then(setMovie).catch(e => setError(e.message)); }, [id]); if (error) return <ErrorState message={error} retry={() => setError('')} />; if (!movie) return <LoadingGrid />; const saved = wishlist.some(item => item.id === movie.id); return <section className="detail"><div>{movie.posterUrl ? <img className="detail-poster" src={movie.posterUrl} alt={`${movie.title} poster`} /> : <div className="detail-poster poster-fallback">{movie.title.slice(0, 1)}</div>}</div><div><Link className="back" to="/">← Back to discovery</Link><h1>{movie.title}</h1><p className="detail-copy">{movie.overview}</p><p>★ {movie.rating?.toFixed(1) ?? 'N/A'} · {movie.releaseDate?.slice(0, 4) ?? 'Unknown year'} {movie.runtimeMinutes ? `· ${movie.runtimeMinutes} min` : ''}</p><div>{movie.genres.map(g => <span className="tag" key={g}>{g}</span>)}</div><button className="primary" onClick={() => toggle(movie)}>{saved ? '♥ Remove from wishlist' : '♡ Add to wishlist'}</button></div></section>; }
export default function App() { return <Layout><Routes><Route path="/" element={<Discover />} /><Route path="/search" element={<SearchPage />} /><Route path="/wishlist" element={<WishlistPage />} /><Route path="/movies/:id" element={<DetailsPage />} /></Routes></Layout>; }
